DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA4MzA1NDMxLCJ1c2VySWQiOjJ9.jpcOYMY9HpmJ0kNF2_h11vv9IBLIVHEetlvgt9gifuI
